spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/krainet_db
    username: ${DB_USERNAME:db_user}
    password: ${DB_PASSWORD:db_password}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true
    validate-on-migrate: true
    out-of-order: false
    clean-disabled: true
    table: flyway_schema_history
    baseline-version: 1
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME:email@example.com}
    password: ${MAIL_PASSWORD:email_password}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

jwt:
  secret: ${JWT_SECRET:your_jwt_secret}
  access-token-ttl: 15m
  refresh-token-ttl: 1d

openapi:
  service:
    title: auth-service doc
    version: 1.0.0
    url: http://localhost:8080

logging:
  level:
    root: INFO
    com.velshletter.auth_service: DEBUG 