spring:
  application:
    name: notification-service
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: notification-group
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME:email@example.com}
    password: ${MAIL_PASSWORD:email_password}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
auth-service:
  url: http://localhost:8080
app:
  mail:
    from: ${MAIL_USERNAME:email@example.com}
server:
  port: 8081


jwt:
  secret: ${JWT_SECRET:jwt_secret}

logging:
  level:
    root: INFO
    com.velshletter.notification_service: DEBUG
